name: code formatting

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
      - run: npm ci
      - run: npx -c 'prettier --check .'
