name: dist

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: tibdex/github-app-token@36464acb844fc53b9b8b2401da68844f6b05ebb0
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: npm ci

      - run: npm run dist

      - uses: ceva24/create-pull-request@a58ca0bbb601044374cd8cb739b12a075a122639
        id: create-pull-request
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Update dist
          branch: update-dist
          delete-branch: true
          title: Update dist
          body: Automated pull request to update dist

      - uses: peter-evans/enable-pull-request-automerge@b0304d26721a2618e8d878de84ed5c8dfa9f8664
        if: steps.cpr.outputs.pull-request-operation == 'created'
        with:
          token: ${{ steps.generate-token.outputs.token }}
          pull-request-number: ${{ steps.create-pull-request.outputs.pull-request-number }}
