name: tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "00 12 * * 1"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: npm test
      - uses: coverallsapp/github-action@8cbef1dea373ebce56de0a14c68d6267baa10b44
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
